<a href="https://colab.research.google.com/github/Deep-of-Machine/Data_analyze/blob/main/2%ED%95%99%EB%85%8413%EB%B0%98_st15_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D9%2C10_pandas2(%EC%88%98%EC%97%85%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#판다스

In [ ]:
import pandas as pd

In [ ]:
#데이터프레임 - 2차원 
df=pd.DataFrame({'날짜':['2000-01-01','2000-01-02','2000-01-03'],
                 '지점':[108, 108, 108],
                 '평균기온':[13.5, 16.2, 16.2],
                 '최저기온':[7.9, 7.9, 13.1],       
                 '최고기온':[20.7, 22, 21.3]})

In [ ]:
df

날짜   지점  평균기온  최저기온  최고기온
0  2000-01-01  108  13.5   7.9  20.7
1  2000-01-02  108  16.2   7.9  22.0
2  2000-01-03  108  16.2  13.1  21.3

In [ ]:
#데이터프레임 - 리스트, index, column 설정

In [ ]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index = [0,1,2], columns = ['c0','c1','c2'])
df

c0  c1  c2
0   1   2   3
1   4   5   6
2   7   8   9

In [ ]:
#인덱스 확인하기

In [ ]:
df.index

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
#컬럼 확인하기

In [ ]:
df.columns

Index(['c0', 'c1', 'c2'], dtype='object')

In [ ]:
#행 인덱스 변경

In [ ]:
df.index=['0번','1번','2번']
df.columns=['n0','n1','n2']

In [ ]:
df

n0  n1  n2
0번   1   2   3
1번   4   5   6
2번   7   8   9

In [ ]:
#행/열 삭제

In [ ]:
df1=df.drop('0번',axis=0) #axis=0생략가능
df1

n0  n1  n2
1번   4   5   6
2번   7   8   9

In [ ]:
df2=df.drop('n0',axis=1)
df2

In [ ]:
df3=df.drop(['0번','2번'],axis=0) #axis=0생략가능
df3

In [ ]:
df4=df.drop(['n0','n2'],axis=1)
df4

In [ ]:
#기존의 값을 변경할 때, 원본 데이터를 수정하는 inplace = True 옵션을 사용하여 변경
#기존 데이터는 두고, 새로운 데이터에 저장할 때에는 명령어 앞에 df1= 처럼 원하는 이름으로 새로운 객체를 만듦

In [ ]:
df.drop(['n0','n2'],axis=1, inplace = True)
df

In [ ]:
#df 변경하기!

In [ ]:
import pandas as pd
exam_data={'수학':[90,80,70],'영어':[98,85,95],'음악':[85,95,100],'체육':[100,90,90]}
df = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df

In [ ]:
#column 추가하기

In [ ]:
df['국어']=80
df

In [ ]:
#column값 변경하기

In [ ]:
df['국어']=[100,100,80]
df

In [ ]:
#행 추가하기

In [ ]:
df.loc['수민']=80
df

In [ ]:
#행 변경하기

In [ ]:
df.loc['수민']=[80,70,90,100]
df

In [ ]:
#원소 값 변경

In [ ]:
df.loc['서준','영어']=100
df

In [ ]:
#행,열 위치 바꾸기(전치)

In [ ]:
df=df.T

In [ ]:
df

In [ ]:
#제자리로
df=df.T

In [ ]:
df

In [ ]:
#인덱스 기준 정렬

In [ ]:
df1=df.sort_index()
df1

In [ ]:
#특정 열 기준 정렬

In [ ]:
df2=df.sort_values(by='영어',ascending=True) #ascending 오름차순 속성
df2

In [ ]:
#df의 평균값 구하기

In [ ]:
df.mean()

In [ ]:
#df의 중간값 구하기

In [ ]:
df.median()

In [ ]:
#df의 상관계수 구하기

In [ ]:
df.corr()

실습해보기1

In [ ]:
#데이터프레임 - 리스트, index, column 설정

In [ ]:
import pandas as pd
jj = pd.DataFrame([[20,25,30],[10,10,5],[5,10,15]], index = ['당근판매량','귤판매량','무판매량'], columns = ['9/24','9/25','9/26'])
jj

9/24  9/25  9/26
당근판매량    20    25    30
귤판매량     10    10     5
무판매량      5    10    15

In [ ]:
#인덱스 확인하기

In [ ]:
jj.index

Index(['당근판매량', '귤판매량', '무판매량'], dtype='object')

In [ ]:
#컬럼 확인하기

In [ ]:
jj.columns

Index(['9/24', '9/25', '9/26'], dtype='object')

In [ ]:
#인덱스, 컬럼 변경
#인덱스 :['당근','귤','무']변경
#컬럼 : ['09-24','09-25','09-26']변경

In [ ]:
jj.index=['당근','귤','무']
jj.columns = ['09-24','09-25','09-26']
jj

09-24  09-25  09-26
당근     20     25     30
귤      10     10      5
무       5     10     15

In [ ]:
#'당근'행 삭제 후 jj1저장

In [ ]:
jj1 = jj.drop('당근', axis=0)
jj1

09-24  09-25  09-26
귤     10     10      5
무      5     10     15

In [ ]:
#'09-24','09-26' 열 삭제 후 jj2저장

In [ ]:
jj2 = jj.drop(['09-24','09-26'], axis=1)
jj2

09-25
당근     25
귤      10
무      10

In [ ]:
#jj 다시 불러오기

In [ ]:
import pandas as pd
jj = pd.DataFrame([[20,25,30],[10,10,5],[5,10,15]], index = ['당근판매량','귤판매량','무판매량'], columns = ['9/24','9/25','9/26'])
jj

9/24  9/25  9/26
당근판매량    20    25    30
귤판매량     10    10     5
무판매량      5    10    15

In [ ]:
#jj에 '9/22' column 추가하기, 판매량은 [40,3,20]

In [ ]:
jj['9/22']=40,3,20
jj

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
귤판매량     10    10     5     3
무판매량      5    10    15    20

In [ ]:
#'포도판매량' index 추가하기, 판매량은 전체 30

In [ ]:
jj.loc['포도판매량'] = 30
jj

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
귤판매량     10    10     5     3
무판매량      5    10    15    20
포도판매량    30    30    30    30

In [ ]:
#'무판매량' index값 [10,10,15,20]으로 변경하기

In [ ]:
jj.loc['무판매량'] = 10,10,15,20
jj

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
귤판매량     10    10     5     3
무판매량     10    10    15    20
포도판매량    30    30    30    30

In [ ]:
#'포도판매량','9/25' 원소 값 25로 변경

In [ ]:
jj.loc['포도판매량','9/25'] = 25
jj

9/24  9/25  9/26  9/22
당근판매량    20    25    30    40
귤판매량     10    10     5     3
무판매량     10    10    15    20
포도판매량    30    25    30    30

In [ ]:
#행,열 위치 바꾸기(전치)하여 jj에 저장

In [ ]:
jj = jj.T
jj

당근판매량  귤판매량  무판매량  포도판매량
9/24     20    10    10     30
9/25     25    10    10     25
9/26     30     5    15     30
9/22     40     3    20     30

In [ ]:
jj

In [ ]:
#인덱스 기준 오름차순 정렬하고 jj1에 저장

In [ ]:
jj1 = jj.sort_index(ascending=True)
jj1

당근판매량  귤판매량  무판매량  포도판매량
9/22     40     3    20     30
9/24     20    10    10     30
9/25     25    10    10     25
9/26     30     5    15     30

In [ ]:
#'당근판매량' 컬럼 기준 오름차순 정렬후 jj2에 저장

In [ ]:
jj1 = jj.sort_values(by='당근판매량',ascending=True)
jj1

당근판매량  귤판매량  무판매량  포도판매량
9/24     20    10    10     30
9/25     25    10    10     25
9/26     30     5    15     30
9/22     40     3    20     30

In [ ]:
#jj의 평균값 구하기

In [ ]:
jj.mean()

당근판매량    28.75
귤판매량      7.00
무판매량     13.75
포도판매량    28.75
dtype: float64

In [ ]:
#jj의 중간값 구하기

In [ ]:
jj.median()

당근판매량    27.5
귤판매량      7.5
무판매량     12.5
포도판매량    30.0
dtype: float64

In [ ]:
#jj의 상관계수 구하기

In [ ]:
jj.corr()

당근판매량      귤판매량      무판매량     포도판매량
당근판매량  1.000000 -0.932294  0.968330  0.292770
귤판매량  -0.932294  1.000000 -0.978232 -0.561951
무판매량   0.968330 -0.978232  1.000000  0.522233
포도판매량  0.292770 -0.561951  0.522233  1.000000

산술연산 - 리스트, 배열 , numpy라이브러리, pandas라이브러리

In [ ]:
#리스트 연산하기

In [ ]:
a=[1,2,3,4,5]
a=a+3 

TypeError: ignored

In [ ]:
a*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
#넘파이 배열 사용하기

In [ ]:
import numpy as np

In [ ]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [ ]:
#b배열 모든 원소에 3더하기

In [ ]:
b+3

array([4, 5, 6, 7, 8])

In [ ]:
#b배열 모든 원소에 3곱하기

In [ ]:
b*3

array([ 3,  6,  9, 12, 15])

In [ ]:
#np.arange()함수로 6부터 10까지의 c배열 만들기

In [ ]:
c=np.arange(6,11)
c

array([ 6,  7,  8,  9, 10])

In [ ]:
#2차원 배열 만들기

In [ ]:
d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#d배열 모양 확인하기

In [ ]:
d.shape

(2, 5)

In [ ]:
#배열 b,c 더하기 함수 add

In [ ]:
np.add(b,c)

array([ 7,  9, 11, 13, 15])

In [ ]:
#배열 b,c 빼기함수 subtract

In [ ]:
np.subtract(b,c)

array([-5, -5, -5, -5, -5])

In [ ]:
#배열 b,c 곱하기함수 multiply

In [ ]:
np.multiply(b,c)

array([ 6, 14, 24, 36, 50])

In [ ]:
#배열 b,c 나누기함수 divide

In [ ]:
np.divide(b,c)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
#numpy 같은 위치의 원소의 계산함.

스스로해보기2

In [ ]:
import numpy as np

In [ ]:
b=np.array([10,20,30,40,50])
b

In [ ]:
#b배열 모든 원소에 3곱하기

In [ ]:
#np.arange()함수로 1부터 5까지의 c배열 만들기

In [ ]:
#배열 c,b 더하기 함수 add

In [ ]:
#배열 c,b 빼기함수 subtract

In [ ]:
#배열 b,c 곱하기함수 multiply

In [ ]:
#배열 b,c 나누기함수 divide

판다스 산술연산

In [ ]:
#시리즈vs숫자 연산

In [ ]:
sr1=pd.Series({'a':1,'b':2,'c':3}) #시리즈1
sr1

a    1
b    2
c    3
dtype: int64

In [ ]:
sr2=pd.Series({'a':4,'b':5,'c':6}) #시리즈1
sr2

a    4
b    5
c    6
dtype: int64

In [ ]:
#sr1에 5 더하기

In [ ]:
sr1+5

In [ ]:
#시리즈vs시리즈 연산 합구하기

In [ ]:
sr1+sr2

In [ ]:
#NaN이 있는 시리즈 연산

In [ ]:
import numpy as np
sr3=pd.Series({'a':np.nan,'b':1,'c':1}) 
sr3

In [ ]:
#sr2 와 sr3 데이터 합하기

In [ ]:
sr2+sr3

In [ ]:
#데이터 프레임 vs 숫자

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]}, index = ['one','two','three'])
df1

a  b  c
one    1  4  7
two    2  5  8
three  3  6  9

In [ ]:
import pandas as pd
df2 = pd.DataFrame({'a':[3,2,1],'b':[6,5,4],'c':[9,8,7]}, index = ['one','two','three'])
df2

a  b  c
one    3  6  9
two    2  5  8
three  1  4  7

In [ ]:
#df1에서 1 빼기

In [ ]:
df-1

In [ ]:
#데이터프레임vs데이터프레임

In [ ]:
#데이터 프레임 간 데이터 합하기

In [ ]:
df1+df2

In [ ]:
#Nan이 있는 데이터 프레임 연산

In [ ]:
import pandas as pd
df3 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'d':[7,8,9]}, index = ['one','two','three'])
df3

In [ ]:
#df2와 df3 의 합

In [ ]:
df2+df3

In [ ]:
#df3의 a+b 값을 e컬럼을 만들어 df3에 추가하기

In [ ]:
df3['e']=df3['a']+df3['b']
df3

스스로해보기

In [ ]:
#시리즈vs숫자 연산

In [ ]:
lib1=pd.Series({'제주':50,'서울':100,'부산':90}) #도서관의 수
lib1

제주     50
서울    100
부산     90
dtype: int64

In [ ]:
lib2=pd.Series({'제주':2,'서울':10,'부산':7}) #1년뒤 추가된 도서관의 수
lib2

제주     2
서울    10
부산     7
dtype: int64

In [ ]:
#제주, 서울, 부산 도서관의 비율(lib1/전체도서관의 수)

In [ ]:
a = lib1/(lib1+lib2)
a

제주    0.961538
서울    0.909091
부산    0.927835
dtype: float64

In [ ]:
#lib1데이터와 lib2데이터 합구하기

In [ ]:
q = lib1 + lib2
q

제주     52
서울    110
부산     97
dtype: int64

In [ ]:
#NaN이 있는 시리즈 연산

In [ ]:
lib3=pd.Series({'제주':np.nan,'서울':1,'부산':2}) #2년뒤 추가된 도서관의 수
lib3

제주    NaN
서울    1.0
부산    2.0
dtype: float64

In [ ]:
#lib2와 lib3데이터 합하기, 결과확인하기

In [ ]:
1 k = lib2 + lib3
k

SyntaxError: ignored

In [ ]:
#데이터프레임vs숫자

In [ ]:
import pandas as pd
exam_data={'수학':[90,80,70],'영어':[98,85,95],'음악':[85,95,100],'체육':[100,90,90]}
df1 = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df1

수학  영어   음악   체육
서준  90  98   85  100
우현  80  85   95   90
인아  70  95  100   90

In [ ]:
import pandas as pd
exam_data={'수학':[70,70,70],'영어':[10,20,40],'음악':[50,55,100],'체육':[70,80,10]}
df2 = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df2

수학  영어   음악  체육
서준  70  10   50  70
우현  70  20   55  80
인아  70  40  100  10

In [ ]:
#df1의 모든 점수에서 -5

In [ ]:
df1-5

수학  영어  음악  체육
서준  85  93  80  95
우현  75  80  90  85
인아  65  90  95  85

In [ ]:
#df1 과 df2 데이터 합구하기

In [ ]:
df1 + df2

수학   영어   음악   체육
서준  160  108  135  170
우현  150  105  150  170
인아  140  135  200  100

In [ ]:
#1차 시험점수, 2차 시험점수 평균 구하기

In [ ]:
(df1 + df2).mean()

수학    150.000000
영어    116.000000
음악    161.666667
체육    146.666667
dtype: float64

In [ ]:
#NaN이 있는 데이터프레임 연산

In [ ]:
#Nan이 있는 df3 생성
import pandas as pd
exam_data={'국어':[10,70,60],'수학':[70,70,70],'영어':[10,20,40],'음악':[50,55,100],'체육':[70,80,10]}
df3 = pd.DataFrame(exam_data, index = ['서준','우현','인아'])
df3

In [ ]:
#df2와 df3 합하여 결과 확인

In [ ]:
#df3의 수학+영어 합 데이터를 df3['수영']컬럼을 만들어 추가하기

<스스로 해보기 프로젝트>

제주 인구데이터 처리하기
'2019제주인구수 데이터에서 총 인구수가 많은 동네와 그 인구수를 구해주세요~'

In [ ]:
#판다스 라이브러리 사용하기

In [ ]:
import pandas as pd

In [ ]:
#엑셀 파일 불러오기

In [ ]:
df=pd.read_excel('./2019제주인구수.xlsx')

In [ ]:
#컬럼 이름 바꾸기 ['동','계','계(남)','계(여)','내(남)','내(여)','외(남)','외(여)']

In [ ]:
df

구 분  합 계 Unnamed: 2 Unnamed: 3     내국인 Unnamed: 5   외국인 Unnamed: 7
0     NaN    계          남          여       남          여     남          여
1   제 주 시  NaN        NaN        NaN  245533     243872  9123       7422
2   한 림 읍  NaN        NaN        NaN   11011      10354  2383       1332
3   애 월 읍  NaN        NaN        NaN   18718      17515   571        541
4   구 좌 읍  NaN        NaN        NaN    8014       7575   440        203
5   조 천 읍  NaN        NaN        NaN   12666      12004   374        269
6   한 경 면  NaN        NaN        NaN    4552       4485   261        107
7   추 자 면  NaN        NaN        NaN     941        792   311         13
8   우 도 면  NaN        NaN        NaN     974        888    19         11
9   일도 1동  NaN        NaN        NaN    1423       1301    43         42
10  일도 2동  NaN        NaN        NaN   16565      17118   102        213
11  이도 1동  NaN        NaN        NaN    3773       3876    56         91
12  이도 2동  NaN        NaN        NaN   24554      25410   305        386
13  삼도 1동  NaN        NaN        NaN    6788       7066    66         85
14  삼도 2동  NaN        NaN        NaN    4254       3920   160         99
15  용담 1동  NaN        NaN        NaN    3714       3511    41         49
16  용담 2동  NaN        NaN        NaN    7580       7494    77        177
17  건 입 동  NaN        NaN        NaN    4774       4537   163         97
18  화 북 동  NaN        NaN        NaN   12413      12442   226        190
19  삼 양 동  NaN        NaN        NaN   12933      12769   101        162
20  봉 개 동  NaN        NaN        NaN    2740       2530    42         51
21  아 라 동  NaN        NaN        NaN   17352      17454   615        603
22  오 라 동  NaN        NaN        NaN    7741       7593   122        132
23    연 동  NaN        NaN        NaN   20376      21137  1062       1133
24  노 형 동  NaN        NaN        NaN   26628      27594  1295       1094
25  외 도 동  NaN        NaN        NaN   11002      10799   125        182
26  이 호 동  NaN        NaN        NaN    2374       2195    95        100
27  도 두 동  NaN        NaN        NaN    1673       1513    68         60

In [ ]:
#데이터 살펴보기

In [ ]:
df1 = df.columns=['동','계', '계(남)','계(여)','내남','내여','외남','외여']
df.drop(df.index[0])

동       계    계(남)    계(여)      내남      내여    외남    외여
1   제 주 시  505950  254656  251294  245533  243872  9123  7422
2   한 림 읍   25080   13394   11686   11011   10354  2383  1332
3   애 월 읍   37345   19289   18056   18718   17515   571   541
4   구 좌 읍   16232    8454    7778    8014    7575   440   203
5   조 천 읍   25313   13040   12273   12666   12004   374   269
6   한 경 면    9405    4813    4592    4552    4485   261   107
7   추 자 면    2057    1252     805     941     792   311    13
8   우 도 면    1892     993     899     974     888    19    11
9   일도 1동    2809    1466    1343    1423    1301    43    42
10  일도 2동   33998   16667   17331   16565   17118   102   213
11  이도 1동    7796    3829    3967    3773    3876    56    91
12  이도 2동   50655   24859   25796   24554   25410   305   386
13  삼도 1동   14005    6854    7151    6788    7066    66    85
14  삼도 2동    8433    4414    4019    4254    3920   160    99
15  용담 1동    7315    3755    3560    3714    3511    41    49
16  용담 2동   15328    7657    7671    7580    7494    77   177
17  건 입 동    9571    4937    4634    4774    4537   163    97
18  화 북 동   25271   12639   12632   12413   12442   226   190
19  삼 양 동   25965   13034   12931   12933   12769   101   162
20  봉 개 동    5363    2782    2581    2740    2530    42    51
21  아 라 동   36024   17967   18057   17352   17454   615   603
22  오 라 동   15588    7863    7725    7741    7593   122   132
23    연 동   43708   21438   22270   20376   21137  1062  1133
24  노 형 동   56611   27923   28688   26628   27594  1295  1094
25  외 도 동   22108   11127   10981   11002   10799   125   182
26  이 호 동    4764    2469    2295    2374    2195    95   100
27  도 두 동    3314    1741    1573    1673    1513    68    60

In [ ]:
#계(남)데이터 채우기

In [ ]:
df['계(남)'] = df['내남']+df['외남']
df

동    계    계(남)    계(여)      내남      내여    외남    외여
0     NaN    계      남남      여여       남       여     남     여
1   제 주 시  NaN  254656  251294  245533  243872  9123  7422
2   한 림 읍  NaN   13394   11686   11011   10354  2383  1332
3   애 월 읍  NaN   19289   18056   18718   17515   571   541
4   구 좌 읍  NaN    8454    7778    8014    7575   440   203
5   조 천 읍  NaN   13040   12273   12666   12004   374   269
6   한 경 면  NaN    4813    4592    4552    4485   261   107
7   추 자 면  NaN    1252     805     941     792   311    13
8   우 도 면  NaN     993     899     974     888    19    11
9   일도 1동  NaN    1466    1343    1423    1301    43    42
10  일도 2동  NaN   16667   17331   16565   17118   102   213
11  이도 1동  NaN    3829    3967    3773    3876    56    91
12  이도 2동  NaN   24859   25796   24554   25410   305   386
13  삼도 1동  NaN    6854    7151    6788    7066    66    85
14  삼도 2동  NaN    4414    4019    4254    3920   160    99
15  용담 1동  NaN    3755    3560    3714    3511    41    49
16  용담 2동  NaN    7657    7671    7580    7494    77   177
17  건 입 동  NaN    4937    4634    4774    4537   163    97
18  화 북 동  NaN   12639   12632   12413   12442   226   190
19  삼 양 동  NaN   13034   12931   12933   12769   101   162
20  봉 개 동  NaN    2782    2581    2740    2530    42    51
21  아 라 동  NaN   17967   18057   17352   17454   615   603
22  오 라 동  NaN    7863    7725    7741    7593   122   132
23    연 동  NaN   21438   22270   20376   21137  1062  1133
24  노 형 동  NaN   27923   28688   26628   27594  1295  1094
25  외 도 동  NaN   11127   10981   11002   10799   125   182
26  이 호 동  NaN    2469    2295    2374    2195    95   100
27  도 두 동  NaN    1741    1573    1673    1513    68    60

In [ ]:
#계(여)데이터 채우기

In [ ]:
df['계(여)'] = df['내여']+df['외여']
df

동    계    계(남)    계(여)      내남      내여    외남    외여
0     NaN    계      남남      여여       남       여     남     여
1   제 주 시  NaN  254656  251294  245533  243872  9123  7422
2   한 림 읍  NaN   13394   11686   11011   10354  2383  1332
3   애 월 읍  NaN   19289   18056   18718   17515   571   541
4   구 좌 읍  NaN    8454    7778    8014    7575   440   203
5   조 천 읍  NaN   13040   12273   12666   12004   374   269
6   한 경 면  NaN    4813    4592    4552    4485   261   107
7   추 자 면  NaN    1252     805     941     792   311    13
8   우 도 면  NaN     993     899     974     888    19    11
9   일도 1동  NaN    1466    1343    1423    1301    43    42
10  일도 2동  NaN   16667   17331   16565   17118   102   213
11  이도 1동  NaN    3829    3967    3773    3876    56    91
12  이도 2동  NaN   24859   25796   24554   25410   305   386
13  삼도 1동  NaN    6854    7151    6788    7066    66    85
14  삼도 2동  NaN    4414    4019    4254    3920   160    99
15  용담 1동  NaN    3755    3560    3714    3511    41    49
16  용담 2동  NaN    7657    7671    7580    7494    77   177
17  건 입 동  NaN    4937    4634    4774    4537   163    97
18  화 북 동  NaN   12639   12632   12413   12442   226   190
19  삼 양 동  NaN   13034   12931   12933   12769   101   162
20  봉 개 동  NaN    2782    2581    2740    2530    42    51
21  아 라 동  NaN   17967   18057   17352   17454   615   603
22  오 라 동  NaN    7863    7725    7741    7593   122   132
23    연 동  NaN   21438   22270   20376   21137  1062  1133
24  노 형 동  NaN   27923   28688   26628   27594  1295  1094
25  외 도 동  NaN   11127   10981   11002   10799   125   182
26  이 호 동  NaN    2469    2295    2374    2195    95   100
27  도 두 동  NaN    1741    1573    1673    1513    68    60

In [ ]:
#계 데이터 채우기

In [ ]:
df['계'] = df['계(남)']+df['계(여)']
df

동       계    계(남)    계(여)      내남      내여    외남    외여
0     NaN    남남여여      남남      여여       남       여     남     여
1   제 주 시  505950  254656  251294  245533  243872  9123  7422
2   한 림 읍   25080   13394   11686   11011   10354  2383  1332
3   애 월 읍   37345   19289   18056   18718   17515   571   541
4   구 좌 읍   16232    8454    7778    8014    7575   440   203
5   조 천 읍   25313   13040   12273   12666   12004   374   269
6   한 경 면    9405    4813    4592    4552    4485   261   107
7   추 자 면    2057    1252     805     941     792   311    13
8   우 도 면    1892     993     899     974     888    19    11
9   일도 1동    2809    1466    1343    1423    1301    43    42
10  일도 2동   33998   16667   17331   16565   17118   102   213
11  이도 1동    7796    3829    3967    3773    3876    56    91
12  이도 2동   50655   24859   25796   24554   25410   305   386
13  삼도 1동   14005    6854    7151    6788    7066    66    85
14  삼도 2동    8433    4414    4019    4254    3920   160    99
15  용담 1동    7315    3755    3560    3714    3511    41    49
16  용담 2동   15328    7657    7671    7580    7494    77   177
17  건 입 동    9571    4937    4634    4774    4537   163    97
18  화 북 동   25271   12639   12632   12413   12442   226   190
19  삼 양 동   25965   13034   12931   12933   12769   101   162
20  봉 개 동    5363    2782    2581    2740    2530    42    51
21  아 라 동   36024   17967   18057   17352   17454   615   603
22  오 라 동   15588    7863    7725    7741    7593   122   132
23    연 동   43708   21438   22270   20376   21137  1062  1133
24  노 형 동   56611   27923   28688   26628   27594  1295  1094
25  외 도 동   22108   11127   10981   11002   10799   125   182
26  이 호 동    4764    2469    2295    2374    2195    95   100
27  도 두 동    3314    1741    1573    1673    1513    68    60

In [ ]:
df = df.drop(df.index[0])

In [ ]:
#인덱스를 동으로 변경하기

In [ ]:
df1 = df.set_index('동')

In [ ]:
#df1데이터에서 '제 주 시' 인덱스 삭제하여 df2에 저장

In [ ]:
df2 = df.drop(df.index[0])

In [ ]:
df2
df2 = df.set_index('동')

In [ ]:
df2= df2.drop(df2.index[0])

In [ ]:
df2

계   계(남)   계(여)     내남     내여    외남    외여
동                                                   
한 림 읍  25080  13394  11686  11011  10354  2383  1332
애 월 읍  37345  19289  18056  18718  17515   571   541
구 좌 읍  16232   8454   7778   8014   7575   440   203
조 천 읍  25313  13040  12273  12666  12004   374   269
한 경 면   9405   4813   4592   4552   4485   261   107
추 자 면   2057   1252    805    941    792   311    13
우 도 면   1892    993    899    974    888    19    11
일도 1동   2809   1466   1343   1423   1301    43    42
일도 2동  33998  16667  17331  16565  17118   102   213
이도 1동   7796   3829   3967   3773   3876    56    91
이도 2동  50655  24859  25796  24554  25410   305   386
삼도 1동  14005   6854   7151   6788   7066    66    85
삼도 2동   8433   4414   4019   4254   3920   160    99
용담 1동   7315   3755   3560   3714   3511    41    49
용담 2동  15328   7657   7671   7580   7494    77   177
건 입 동   9571   4937   4634   4774   4537   163    97
화 북 동  25271  12639  12632  12413  12442   226   190
삼 양 동  25965  13034  12931  12933  12769   101   162
봉 개 동   5363   2782   2581   2740   2530    42    51
아 라 동  36024  17967  18057  17352  17454   615   603
오 라 동  15588   7863   7725   7741   7593   122   132
연 동    43708  21438  22270  20376  21137  1062  1133
노 형 동  56611  27923  28688  26628  27594  1295  1094
외 도 동  22108  11127  10981  11002  10799   125   182
이 호 동   4764   2469   2295   2374   2195    95   100
도 두 동   3314   1741   1573   1673   1513    68    60

In [ ]:
#df1데이터를 가나다 순 정렬하여 df3에 저장

In [ ]:
df3 = df1.sort_index(ascending=True)

In [ ]:
df3

계    계(남)    계(여)      내남      내여    외남    외여
동                                                        
건 입 동    9571    4937    4634    4774    4537   163    97
구 좌 읍   16232    8454    7778    8014    7575   440   203
노 형 동   56611   27923   28688   26628   27594  1295  1094
도 두 동    3314    1741    1573    1673    1513    68    60
봉 개 동    5363    2782    2581    2740    2530    42    51
삼 양 동   25965   13034   12931   12933   12769   101   162
삼도 1동   14005    6854    7151    6788    7066    66    85
삼도 2동    8433    4414    4019    4254    3920   160    99
아 라 동   36024   17967   18057   17352   17454   615   603
애 월 읍   37345   19289   18056   18718   17515   571   541
연 동     43708   21438   22270   20376   21137  1062  1133
오 라 동   15588    7863    7725    7741    7593   122   132
외 도 동   22108   11127   10981   11002   10799   125   182
용담 1동    7315    3755    3560    3714    3511    41    49
용담 2동   15328    7657    7671    7580    7494    77   177
우 도 면    1892     993     899     974     888    19    11
이 호 동    4764    2469    2295    2374    2195    95   100
이도 1동    7796    3829    3967    3773    3876    56    91
이도 2동   50655   24859   25796   24554   25410   305   386
일도 1동    2809    1466    1343    1423    1301    43    42
일도 2동   33998   16667   17331   16565   17118   102   213
제 주 시  505950  254656  251294  245533  243872  9123  7422
조 천 읍   25313   13040   12273   12666   12004   374   269
추 자 면    2057    1252     805     941     792   311    13
한 경 면    9405    4813    4592    4552    4485   261   107
한 림 읍   25080   13394   11686   11011   10354  2383  1332
화 북 동   25271   12639   12632   12413   12442   226   190

In [ ]:
#df2에서 전체 인구가 가장 많은 동 을 정렬하고 df4에 저장

In [ ]:
df4 = df2.sort_values(by='계', ascending=False)

In [ ]:
df4

계   계(남)   계(여)     내남     내여    외남    외여
동                                                   
노 형 동  56611  27923  28688  26628  27594  1295  1094
이도 2동  50655  24859  25796  24554  25410   305   386
연 동    43708  21438  22270  20376  21137  1062  1133
애 월 읍  37345  19289  18056  18718  17515   571   541
아 라 동  36024  17967  18057  17352  17454   615   603
일도 2동  33998  16667  17331  16565  17118   102   213
삼 양 동  25965  13034  12931  12933  12769   101   162
조 천 읍  25313  13040  12273  12666  12004   374   269
화 북 동  25271  12639  12632  12413  12442   226   190
한 림 읍  25080  13394  11686  11011  10354  2383  1332
외 도 동  22108  11127  10981  11002  10799   125   182
구 좌 읍  16232   8454   7778   8014   7575   440   203
오 라 동  15588   7863   7725   7741   7593   122   132
용담 2동  15328   7657   7671   7580   7494    77   177
삼도 1동  14005   6854   7151   6788   7066    66    85
건 입 동   9571   4937   4634   4774   4537   163    97
한 경 면   9405   4813   4592   4552   4485   261   107
삼도 2동   8433   4414   4019   4254   3920   160    99
이도 1동   7796   3829   3967   3773   3876    56    91
용담 1동   7315   3755   3560   3714   3511    41    49
봉 개 동   5363   2782   2581   2740   2530    42    51
이 호 동   4764   2469   2295   2374   2195    95   100
도 두 동   3314   1741   1573   1673   1513    68    60
일도 1동   2809   1466   1343   1423   1301    43    42
추 자 면   2057   1252    805    941    792   311    13
우 도 면   1892    993    899    974    888    19    11

In [ ]:
#가장 인구가 많은 동 5개 뽑아 df5에 저장하기

In [ ]:
df5=df4.iloc[0:5]
df5

계   계(남)   계(여)     내남     내여    외남    외여
동                                                   
노 형 동  56611  27923  28688  26628  27594  1295  1094
이도 2동  50655  24859  25796  24554  25410   305   386
연 동    43708  21438  22270  20376  21137  1062  1133
애 월 읍  37345  19289  18056  18718  17515   571   541
아 라 동  36024  17967  18057  17352  17454   615   603

In [ ]:
#max_dong에 인구가 많은 동 저장, max_pop에 총 인구수 저장

In [ ]:
max_dong = df4.iloc[0]

In [ ]:
max

계       56611
계(남)    27923
계(여)    28688
내남      26628
내여      27594
외남       1295
외여       1094
Name: 노 형 동, dtype: object

In [ ]:
#가장 인구가 많은 동은 ~ 동이고, 총 ~ 이 거주하고 있다. 출력

In [ ]:
print('가장 인구가 많은 동은',max_dong,'이고, 총',max_pop,'명이 거주하고 있다.')